# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z7aGkTHnAqEtMRmhyw-ZwDRDwFa3nn6M
"""

tasks = []

while True:
    task = input("Enter a task (or type 'done' to finish): ")

    if task.lower() == "done":
        break

    tasks.append(task)

print("\nYour To-Do List:")
for i, task in enumerate(tasks, start=1):
    print(f"{i}. {task}")