# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z7aGkTHnAqEtMRmhyw-ZwDRDwFa3nn6M
"""

# Expense Tracker

total = 0

print("Expense Tracker")
print("Enter your expenses one by one.")
print("Type 0 to stop.\n")

while True:
    expense = float(input("Enter expense amount: "))

    if expense == 0:
        break

    total = total + expense

print("\nTotal Amount Spent:", total)