# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z7aGkTHnAqEtMRmhyw-ZwDRDwFa3nn6M
"""

import random
import string

def generate_password(length):
    # Combine letters (upper + lower), digits, and punctuation
    characters = string.ascii_letters + string.digits + string.punctuation

    # Randomly pick 'length' characters from the pool
    password = ''.join(random.choice(characters) for _ in range(length))

    return password

def main():
    print("=== Random Password Generator ===")

    while True:
        try:
            length = int(input("Enter desired password length (e.g., 8): "))
            if length <= 0:
                print("Please enter a positive number.")
                continue
            break
        except ValueError:
            print("Invalid input. Please enter a number.")

    password = generate_password(length)
    print(f"\nYour generated password is: {password}")

if __name__ == "__main__":
    main()